"""Add carrier column to User

Revision ID: 123051c17844
Revises: 
Create Date: 2025-02-15 15:09:12.124156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123051c17844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('favorite_lines', sa.TEXT(), nullable=True),
    sa.Column('notification_settings', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###
